version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isucondition
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./webapp/sql:/sql
  go:
    image: golang:1.16
    restart: always
    working_dir: /home/isucon/isucon11-qualify
    volumes:
      - ./webapp:/home/isucon/isucon11-qualify
    command: bash -c "cd go && go run main.go"
    ports:
      - "3000:3000"
    environment:
      POST_ISUCONDITION_TARGET_BASE_URL: https://isucondition-1.t.isucon.dev
      MYSQL_HOST: db
      ISUCONDITION_DEBUG: 1

  frontend:
    image: node:14.17.0
    restart: always
    working_dir: /home/isucon/isucon11-qualify/webapp
    volumes:
      - ./webapp/frontend:/home/isucon/isucon11-qualify/webapp
    command: bash -c "npm run dev"
    ports:
      - "3333:3333"
    
volumes:
  db_data:
